name: fluttershare
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.9.7+2
  image_picker: ^0.6.0+2
  firebase_storage: ^2.1.0+1
  firebase_auth: ^0.8.3
  google_sign_in: ^4.0.1+1
  geolocator: 5.0.1
  uuid: ^2.0.0
  image: ^2.0.7
  animator: ^2.0.1
  cupertino_icons: ^0.1.2
  path_provider: ^1.6.9
  firebase_messaging: ^4.0.0+1
  timeago: 2.0.17
  fluttertoast: ^4.0.1
  flutter_easyloading: ^1.1.4
  cached_network_image:
  flutter_svg:
  flutter_localizations:
    sdk: flutter
  chewie: ^0.9.10
  provider: ^4.1.2
  auto_size_text: ^2.1.0

  shared_preferences: 0.5.7+2
  youtube_player_flutter: 6.1.1
  flutter_local_notifications: ^1.4.3
  rxdart: ^0.24.1
  lottie:
  dartx: ^0.4.1
  characters:
  connectivity: 0.4.8+6
  video_player: 0.10.11+1
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  rflutter_alert: ^1.0.3
  photo_view: 0.9.2

dev_dependencies:
  # hive_generator: ^0.7.0+2
  build_runner: ^1.10.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: Lemonada
      fonts:
        - asset: assets/fonts/Lemonada.ttf
  assets:
    - assets/images/google_signin_button.png
    - lib/lang/en.json
    - lib/lang/ar.json
    - assets/images/search.svg
    - assets/images/upload.svg
    - assets/images/pencil.png
    - assets/images/title.png
    - assets/images/cbt.png
    - assets/images/depr.jpg
    - assets/images/foc.png
    - assets/images/hear.png
    - assets/images/help.png
    - assets/images/nerv.jpg
    - assets/images/over.png
    - assets/images/guide.jpeg
    - assets/images/social-anexity.png
    - assets/images/self-regular.png
    - assets/animations/12833-planta-3.json
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/5.png
    - assets/images/6.png
    - assets/images/7.png
    - assets/images/8.png
    - assets/images/9.png
    - assets/images/10.png
    - assets/images/11.png
    - assets/images/stairs.jpg
    - assets/images/reward.png
    - assets/images/lock.png
    - assets/images/flower.png
    - assets/images/hero.png
    - assets/animations/12833-planta-3.json
    - assets/animations/bar.json
    - assets/animations/doing_well.json
    - assets/animations/first_message.json
    - assets/animations/first.json
    - assets/animations/cant.json
    - assets/animations/hero_bar.json
    - assets/animations/hero_message.json
