name: fluttershare
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.6
  image_picker: ^0.6.0+2
  firebase_storage: ^3.1.6
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  geolocator: 5.0.1
  uuid: ^2.0.0
  image: ^2.0.7
  animator: ^2.0.1
  cupertino_icons: ^0.1.2
  path_provider: ^1.6.9
  firebase_messaging: ^6.0.16
  timeago: 2.0.17
  fluttertoast: ^4.0.1
  flutter_easyloading: ^1.1.4
  cached_network_image:
  flutter_svg:
  flutter_localizations:
    sdk: flutter
  chewie: ^0.9.10
  provider: ^4.1.2
  auto_size_text: ^2.1.0
  carousel_slider: ^2.1.0
  firebase_database: ^3.1.6
  firebase_core: ^0.4.5
  shimmer: ^1.1.1
  step_progress_indicator: ^0.2.3+6
  status_alert: ^0.1.2

  shared_preferences: 0.5.7+2
  youtube_player_flutter: 6.1.1
  flutter_local_notifications: ^1.4.3
  rxdart: ^0.24.1
  lottie: ^0.4.0+1
  dartx: ^0.4.1
  characters:
  connectivity: 0.4.8+6
  video_player: 0.10.11+1
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  rflutter_alert: ^1.0.1
  photo_view: 0.9.2
  http:
  sticky_headers: ^0.1.8+1


dev_dependencies:
  # hive_generator: ^0.7.0+2
  build_runner: ^1.10.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: Lemonada
      fonts:
        - asset: assets/fonts/Lemonada.ttf
    - family: Tajwal
      fonts:
       - asset: assets/fonts/Tajwal.ttf
  assets:
    - assets/images/
    - assets/animations/
    - lib/lang/en.json
    - lib/lang/ar.json
    # - assets/images/search.svg
    # - assets/images/upload.svg
    # - assets/images/pencil.png
    # - assets/images/title.png
    # - assets/animations/12833-planta-3.json
    # - assets/images/reward.png
    # - assets/images/lock.png
    # - assets/images/flower.png
    # - assets/images/hero.png
    # - assets/animations/12833-planta-3.json
    # - assets/animations/bar.json
    # - assets/animations/doing_well.json
    # - assets/animations/first_message.json
    # - assets/animations/first.json
    # - assets/animations/cant.json
    # - assets/animations/hero_bar.json
    # - assets/animations/hero_message.json
    # - assets/images/body1.png
    # - assets/images/body.png
    # - assets/images/brain.png
    # - assets/images/lungs.png
    # - assets/images/eyes1.png
    # - assets/images/heart.png
    # - assets/images/stomach.png
    # - assets/images/contact.png
    # - assets/animations/music.json
    # - assets/animations/flower.json
    # - assets/animations/muscle.json
    # - assets/images/sad_tree.png
    # - assets/images/logo.png
